#' Plot all selected workouts on an interactive leaflet map.
#'
#' @param sumX An object of class \code{trackeRdataSummary}.
#' @param threshold Logical. Should thresholds be applied?
#' @param df A dataframe (optional). A user can provide a dataframe generated by \code{prepRoute}.
#' @param all_sessions A vector of sessions being plotted.
#' @param colour_sessions A vector of sessions to be colour to orange.
plot_map <- function(sumX, df = NULL, threshold = TRUE, all_sessions, colour_sessions) {
    ## if (all(all_sessions %in% colour_sessions)) {
    ##     colour_sessions <-  NULL
    ## }
    ## prepare popups
    opts <- trops()
  units <- collect_units(get_units(sumX), unit_reference_sport = 'cycling')
  popupText <- function(session, start = TRUE, speed) {
    session <- unique(session)
    w <- which(sumX$session == session)
    unitDist4pace <- strsplit(
      units$unit[units$variable == "pace"],
      split = "_per_"
    )[[1]][2]
    avgPace <- floor(sumX$avgPace[w] * 100) / 100

    paste(
      paste("Session:", session),
      # paste(sumX$sessionStart[w], "-", sumX$sessionEnd[w]),
      paste("Distance:", round(sumX$distance[w], 2), units$unit[units$variable == "distance"]),
      paste("Duration:", round(as.numeric(sumX$duration[w]), 2), units$unit[units$variable == "duration"]),
      paste(
        paste0("Avg. pace (per 1 ", unitDist4pace, "):"),
        paste(floor(avgPace), round(avgPace %% 1 * 60, 0), sep = ":"), "min:sec"
      ),
      paste("Current speed:", round(speed, 1), lab_sum(feature = "avgSpeed", data = sumX, whole_text = FALSE)),
      sep = "\n"
    )
  }
    p <- plot_mapbox()
  for (i in all_sessions) {
    plot_df <- df[which(df$SessionID == i), ]
    df_markers <- plot_df[round(seq(1, nrow(plot_df), length.out = 10)), ] #seq(1, nrow(plot_df), round(nrow(plot_df) / 10, 0)), ]
    df_markers$true_session_id <- i

    p <- add_markers(
      p,
      data = df_markers, x = ~ longitude, y = ~ latitude, alpha = 0,
      size = I(0.1), key = ~ true_session_id
    )
    colour <- ifelse(i %in% colour_sessions,
                     opts$summary_plots_selected_colour,
                     opts$summary_plots_deselected_colour)
    p <- add_paths(
        p,
        data = plot_df, x = ~ longitude, y = ~ latitude,
        size = I(2), color = I(colour),
        opacity = 0.3,
        text = ~ popupText(session = SessionID, speed = speed))
  }

  # ## add trace + markers + popups
  # if (!(identical(all_sessions, session))) {
  #   for (i in session) {
  #     plot_df <- df[which(df$SessionID == i), ]
  #     df_markers <- plot_df[seq(1, nrow(plot_df), round(nrow(plot_df) / 10, 0)), ]
  #     df_markers$true_session_id <- i
  #     p <- add_markers(
  #       p, data = df_markers, x = ~longitude, y = ~latitude,
  #       size = I(2), key = ~true_session_id, color = I("darkorange3")
  #     )
  #     p <- add_paths(
  #       p, data = plot_df, x = ~longitude, y = ~latitude,
  #       size = I(2), color = I("darkorange3"),
  #       text = ~popupText(session = SessionID, speed = speed)
  #     )
  #   }
  # }
  center_lat <- ifelse(is.null(colour_sessions), median(df$latitude),
                       median(df$latitude[df$SessionID %in% colour_sessions]))
  center_lon <- ifelse(is.null(colour_sessions), median(df$longitude),
                       median(df$longitude[df$SessionID %in% colour_sessions]))

  # map style buttons
  basic <- list(
    method = "relayout",
    args = list(list(mapbox.style = "basic")),
    label = "Basic"
  )

  dark <- list(
    method = "relayout",
    args = list(list(mapbox.style = "dark")),
    label = "Dark"
  )

  button <- function(map_type, label) {
    list(
      method = "relayout",
      args = list(list(mapbox.style = map_type)),
      label = label
    )
  }

  updatemenus <- list(
    list(
      type = "buttons",
      direction = "right",
      yanchor = "bottom",
      pad = list("r" = 10, "t" = 10, "b" = 10),
      x = 1,
      y = 0,
      buttons = list(
        button("basic", "Basic"), button("streets", "Streets"),
        button("outdoors", "Outdoors"), button("light", "Light"),
        button("dark", "Dark"), button("satellite", "Satellite"),
        button("satellite-streets", "Satellite streets")
      )
    )
  )

  diff_lon <- abs(max(df$longitude) - min(df$longitude))

  p <- layout(
    p,
    mapbox = list(
      zoom = 9,
      center = list(lat = center_lat, lon = center_lon),
      style = "dark"
    ), dragmode = "pan", showlegend = FALSE, updatemenus = updatemenus,
    margin = list(l = 0, r = 0, t = 0, b = 0)
  )
  return(p)
}
